spring:
  freemarker:
    suffix: .ftl
    allow-request-override: true
    cache: false
    check-template-location: true
    template-loader-path: classpath:/templates/views/
    request-context-attribute: request
  shiro:
    redis-nodes: Redis[localhost:6379]
    enable-shiro-realm: true
    enable-unauthorized-redirect: false
    login-success-redirect-url: /index
    enable-anonymous: true
    login-url: /login
    logout-url: /logout
    logout-success-redirect-url: /login
    unauthorized-redirect-url: /403
server:
  port: 9091